### ISSUE TITLE
Can't place a normal hopper in place of a filtered one

### ISSUE THREAD

**Issue by TheChilliPL** [poiNt3D/SortingHopper2#6]
If I place a normal hopper, from creative inventory into a place that was a filtered hopper, the hopper gets filtered.
![image](https://user-images.githubusercontent.com/18823939/86590553-1c58d100-bf90-11ea-8a92-d32146a00bf8.png)
![image](https://user-images.githubusercontent.com/18823939/86590563-25e23900-bf90-11ea-9d4f-e662536ddc6f.png)
Does the same if broken on survival

**Comment by poiNt3D** [comment]
`		if (event.getPlayer().getGameMode() == GameMode.CREATIVE) {
			return;
		}`
I think, this was intended, if if you running around in creative, you wouldn't loose sorting rules on accidental click. 
Switch to survival to properly remove it. Or i could add a config setting to disable this behavior.

**Comment by TheChilliPL** [comment]
Or at least some command to remove the filters
Or maybe removing hopper filters if they're empty?

**Comment by poiNt3D** [comment]
> Or maybe removing hopper filters if they're empty?

Great idea.

**Comment by poiNt3D** [comment]
Fixed
