### ISSUE TITLE
"Wrong item" upon placement - Minecraft 1.16 - Spigot

### ISSUE THREAD

**Issue by strong99** [poiNt3D/SortingHopper2#7]
I'm trying to run the plugin's latest version on Spigot 1.16.1 beta and the plugin keeps telling "[SortingHopper] Wrong item. Use crafting recipe.". It's installed on a latest version of spigot as the only plugin. I checked the [source that produces the error](https://github.com/poiNt3D/SortingHopper2/blob/master/src/point3d/sortinghopper2/PlaceListener.java) but I did not understand why the check that produces the error exists. 

It seems the material type should not be a hopper and named as the recipe? Does that differ from the recipe in older versions?

The item is created through recipe or /give command. Both do not work as they produce the same item using the name of the first entry from the config.yml.

What could be different in 1.16?

**Comment by poiNt3D** [comment]
Hello.
Try setting check_lore to false in config.

> 

`public static boolean checkItem(ItemStack item) {
		if(item.getType().equals(Material.HOPPER) && item.hasItemMeta()) {
			if(check_lore) {
				return item.getItemMeta().getLore().equals(sorter_lore);
			}
			else {
				return sorter_names.contains(item.getItemMeta().getDisplayName());
			}
		}
		else return false;
	}`

It is made this way because some people don't want their players to obtain sorters by just renaming on the anvil. If the item lore isn't equal to the lore you have set in config, it will produce "wrong item" message. If you change the lore setting in your config while players already have crafted sorters, it will make them invalid.
You can avoid lore check by setting check_lore to false.

**Comment by strong99** [comment]
I have not changed anything in the default config. Is seems check_lore is already false by default.

```
# Names used to distinguish sorting hoppers from a normal hoppers.
# The first name in the list wll be used in the crafting recipe.
names:
  - Item Sorter
  - Sorter
  - Filter
...
# Lore is the item description.
# Players cannot change lore without commands.
# If you want to prevent players making sorters by renaming hoppers on the anvil, set check_lore to true
check_lore: false
lore: 
  - "Only selected items will go through."
  - "Rightclick to show rules"
  - "Shift+rightclick with an empty hand to show hopper inventory."
```

**Comment by poiNt3D** [comment]
Hmm.. I'll have to check that. But my main computer is broken right now, it will have to wait : - (

**Comment by poiNt3D** [comment]
Also try deleting your config and restart.

**Comment by strong99** [comment]
I had already created a clean/new server before posting.

I set up a debug version to debug. I added a log to the CheckItem and noticed these §r prefixes on the sorter names but not on the display name:
> "[SortingHopper2] Item in hand display name: 'Item Sorter'. Expected sorter names: '§rItem Sorter', '§rSorter', '§rFilter'"

```
var name = item.getItemMeta().getDisplayName();
var names = String.join(", ", sorter_names);
logger.info("Item in hand display name: " + name + ". Expected sorter names:" +  names);
return sorter_names.contains(name);
```
_Part of Sorter.java. CheckItem(), starting line 72_

**Comment by poiNt3D** [comment]
Thanks.

**Comment by poiNt3D** [comment]
https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-6013?filter=allissues

**Comment by poiNt3D** [comment]
Fixed
